root = "."
tmp_dir = "tmp"
env_files = [".env", ".env.dev"]

[build]
cmd = "DEVMODE=1 make bin/phoenix-server"
entrypoint = ["./bin/phoenix-server"]
exclude_regex = ["_test\\.go"]

[build.windows]
entrypoint = ["bin\\phoenix-server.exe"]

[log]
time = true

[screen]
clear_on_rebuild = true
keep_scroll = true
