-- +goose Up
CREATE TABLE product_images (
	id TEXT PRIMARY KEY,
	product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
	image TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

-- +goose Down
DROP TABLE product_images;
