-- +goose Up
CREATE TABLE shippings (
	id TEXT PRIMARY KEY,
	from_id TEXT REFERENCES users(id) ON DELETE SET NULL,
	to_id TEXT REFERENCES users(id) ON DELETE SET NULL,
	fee NUMERIC(10, 2) NOT NULL,
	location TEXT NOT NULL,
	note TEXT,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

-- +goose Down
DROP TABLE shippings;
