CREATE TABLE users (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	email TEXT NOT NULL UNIQUE,
	phone TEXT NOT NULL UNIQUE,
	role INTEGER NOT NULL DEFAULT 10,
	city TEXT NOT NULL,
	governorate TEXT NOT NULL,
	address TEXT NOT NULL,
	birthdate TIMESTAMP WITH TIME ZONE NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX users_email_idx ON users (email);
CREATE INDEX users_phone_idx ON users (phone);

CREATE TABLE user_bans (
	id INTEGER PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	moderator_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	reason TEXT NOT NULL,
	message TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE product_categories (
	id INTEGER PRIMARY KEY,
	category TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE products (
	id INTEGER PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	name TEXT NOT NULL,
	category INTEGER REFERENCES product_categories(id) ON DELETE SET NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE product_images (
	id INTEGER PRIMARY KEY,
	product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
	image TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE product_tags (
	id INTEGER PRIMARY KEY,
	product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
	tag TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE product_reviews (
	id INTEGER PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
	rating INTEGER NOT NULL,
	comment TEXT NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE shippings (
	id INTEGER PRIMARY KEY,
	from_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	to_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	fee NUMERIC(10, 2) NOT NULL,
	location TEXT NOT NULL,
	note TEXT,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);

CREATE TYPE invoice_status AS ENUM ('pending', 'delivered', 'cancelled');
CREATE TABLE invoices (
	id INTEGER PRIMARY KEY,
	user_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
	product_id INTEGER REFERENCES products(id) ON DELETE SET NULL,
	status invoice_status NOT NULL DEFAULT 'pending',
	note TEXT,
	created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
	deleted_at TIMESTAMP WITH TIME ZONE
);
